### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by steenerson** [markmaker/pcb-placer#1]
Hi,

I'm trying to run this on a fully updated windows 10 machine on firefox/chrome/IE and getting access denied in all cases. I think I've tried setting everything as permissive as possible in the security settings for IE and haven't gotten anywhere. Do you know of a browser/version where this is currently working, or anything else I could try?

I downloaded it more than a year ago and was able to get it working, not sure what has changed.

Thanks!

**Comment by markmaker** [comment]
Hi @steenerson,

Yes, security becomes tighter and tighter.

For Firefox, see here "Local File Security in Firefox 68":
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

I found no other way than to disable this new restriction with `privacy.file_unique_origin` in `about:config`.

![grafik](https://user-images.githubusercontent.com/9963310/75610089-822edb00-5b0e-11ea-9abc-870691e5b54b.png)

Be aware that they changed this for a reason, so you are poking a tiny hole into your security shield there. 

(Other browsers I don't use and can't help with, sorry).

_Mark

**Comment by steenerson** [comment]
This is great, I have it working in firefox with no issues. Thanks! This should save a lot of time for me.
